HEADERS = {
    "Connection": "keep-alive",
    "sec-ch-ua": '"Chromium";v="122", "Not(A:Brand";v="24", "Android WebView";v="122"',
    "sec-ch-ua-mobile": '?1',
    "User-Agent": "Mozilla/5.0 (Linux; Android 11; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36", # noqa E501
    "sec-ch-ua-platform": '"Android"',
    "Accept": "*/*",
    "Origin": "https://hamsterkombatgame.io",
    "X-Requested-With": "org.telegram.messenger",
    "Sec-Fetch-Site": "same-site",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Dest": "empty",
    "Referer": "https://hamsterkombatgame.io/",
    "Accept-Encoding": "gzip, deflate, br",
}

MINI_GAMES = {
    'Train Miner': 'c4480ac7-e178-4973-8061-9ed5b2e17954',
    'Bike Ride 3D': '43e35910-c168-4634-ad4f-52fd764a843f',
    'My Clone Army': 'fe693b26-b342-4159-8808-15e3ff7f8767',
    'Chain Cube 2048': 'b4170868-cef0-424f-8eb9-be0622e8e8e3',
}
MORSE_CODE_DICT = {
    'A': '.-',
    'B': '-...',
    'C': '-.-.',
    'D': '-..',
    'E': '.',
    'F': '..-.',
    'G': '--.',
    'H': '....',
    'I': '..',
    'J': '.---',
    'K': '-.-',
    'L': '.-..',
    'M': '--',
    'N': '-.',
    'O': '---',
    'P': '.--.',
    'Q': '--.-',
    'R': '.-.',
    'S': '...',
    'T': '-',
    'U': '..-',
    'V': '...-',
    'W': '.--',
    'X': '-..-',
    'Y': '-.--',
    'Z': '--..',
    '1': '.----',
    '2': '..---',
    '3': '...--',
    '4': '....-',
    '5': '.....',
    '6': '-....',
    '7': '--...',
    '8': '---..',
    '9': '----.',
    '0': '-----',
    ', ': '--..--',
    '.': '.-.-.-',
    '?': '..--..',
    '/': '-..-.',
    '-': '-....-',
    '(': '-.--.',
    ')': '-.--.-',
}
